---
title: "HW3"
output: html_document
---
##Load relevant packages
```{r}
library(GEOquery)
library(limma)
library(pheatmap)
library(lumi)
```

##Get data from GEO
```{r}
gds <- getGEO("GSE40812",destdir=".")
```

##CLeaning data
Keeping necessary columns, only Macrophage data
```{r}
pd<-pData(gds[[1]])
pd2 <- pd[pd$source_name_ch1=="Monocyte-derived Macrophage",]
pd3<-pd2[c("title", "geo_accession", "characteristics_ch1", "characteristics_ch1.1", "characteristics_ch1.2")]
library(plyr)
pd4<-rename(pd3, c("title"="ptid", "characteristics_ch1"="infection.status", "characteristics_ch1.1"="cell.type", "characteristics_ch1.2"="treatment"))
pd4$infection.status <- gsub(".*: ", "", pd4$infection.status)
pd4$cell.type <- gsub(".*: ", "", pd4$cell.type)
pd4$treatment <- gsub(".*: ", "", pd4$treatment)
pd4$ptid <- sapply(strsplit(as.character(pd4$ptid),"_"), function(x) x[[2]])
pdeset<-gds[, rownames(pd4)]
```

##Normalize the data
Already normalized, but otherwise could use
```{r}
#pd4 <- lumiN(pd4)
```

##Use limma to test for differential expression
Only include FDR cutoff 0.05 and 1.5 fold change at least
```{r}
mm <- model.matrix(~treatment,pd4)
fit <- lmFit(pdeset, mm)
eb <- eBayes(fit)
tt1<- topTable(eb, coef="treatmentPoly IC H", number=Inf, sort.by="none")
tt2<- tt1[tt1$adj.P.Val < 0.05 & abs(tt1$logFC)>log2(1.5), ]
#tt2 contains 1146 probes
```

##Expression based on HCV infection status
```{r}
mm2<-model.matrix(~infection.status, tt2)
fit2<-lmFit(tt2,mm2)
eb2<-eBayes(fit2)
tt3<-topTable(eb2, coef="statusPos", number=Inf, sort.by="none")
tt4<-tt2[tt3$P.Value<0.1]
```

##Order data and create heatmap
```{r}
tabl<-pData(tt4)
tabsort<-tabl[order(tabl$treatment, tabl$infection.status, tabl$ptid), ]
colnames(tabsort)<-tabl$ptid
heatmap(exprs(tabsort))
```